var commonHeader = require('home:widget/ui/header/header.js');
var tpls = {
    content: [
        // '<div class="mod-shopping-order">',
            commonHeader({
              backUrl: '/#shopping/cart',
              title: '提交订单'
            }),
            /* 收货地址 */
            '<div class="weui_cells{{if !add_order_id || order_info.money >= money_info.order_min_money}} weui_cells_access{{/if}} address">',
                '{{if add_order_id && order_info.money < money_info.order_min_money}}',
                    '<div class="weui_cell">',
                '{{else}}',
                    '<a href="/#my/address/select/{{order_info.address_info.address_id}}" class="weui_cell">',
                '{{/if}}',
                        '<div class="weui_cell_primary">',
                            '<i class="icon i-order-address"></i>',
                            '<div class="address-info" data-id="{{order_info.address_info.address_id}}">',
                                '<p class="contact-info">',
                                    '{{order_info.address_info.contact_name}} {{order_info.address_info.contact_phone}}',
                                    '{{if add_order_id && order_info.money < money_info.order_min_money}}',
                                        '<span class="add-order-tip">补单收货地址不可修改</span>',
                                    '{{/if}}',
                                '</p>',
                                '<p class="detail-info">',
                                    '{{order_info.address_info.county_name+order_info.address_info.address}}',
                                '</p>',
                            '</div>',
                        '</div>',
                        '<div class="weui_cell_ft"> </div>',
                '{{if add_order_id && order_info.money < money_info.order_min_money}}',
                    '</div>',
                '{{else}}',
                    '</a>',
                '{{/if}}',
            '</div>',
            /* 支付方式 */
            '<div class="weui_cells">',
                '<div class="pay-mode weui_cell">',
                    '<div class="weui_cell_primary">',
                        '<p>{{order_info.pay_method.title}}</p>',
                    '</div>',
                    '<div class="weui_cell_ft">{{order_info.pay_method.value}}</div>',
                '</div>',
            '</div>',
            /* 优惠券 */
            '<div class="weui_cells weui_cells_access coupon">',
                '<a href="/#my/coupon/select{{if no_coupon || no_usable}}/-1{{else if coupon_list && coupon_list[0]}}/{{coupon_list[0].coupon_id}}{{/if}}?type=1" class="weui_cell" data-id="{{if no_coupon}}-1{{else if coupon_list && coupon_list[0]}}{{coupon_list[0].coupon_id}}{{/if}}">',
                    '<div class="weui_cell_primary">优惠券</div>',
                    '<div class="weui_cell_ft">{{if no_coupon}}不使用优惠券{{else}}{{if coupon_list && coupon_list[0]}}-￥{{coupon_list[0].coupon_money}}{{else}}暂无可用优惠券{{/if}}{{/if}}</div>',
                '</a>',
            '</div>',
            /*现金券*/
            '<div class="weui_cells weui_cells_access cash-coupon">',
                '<a href="/#my/coupon/select{{if no_cash_coupon || no_cash_usable}}/-1{{else if cash_coupon_list && cash_coupon_list[0]}}/{{cash_coupon_list[0].coupon_id}}{{/if}}?type=2" class="weui_cell" data-id="{{if no_cash_coupon}}-1{{else if cash_coupon_list && cash_coupon_list[0]}}{{cash_coupon_list[0].coupon_id}}{{/if}}">',
                    '<div class="weui_cell_primary">现金券</div>',
                    '<div class="weui_cell_ft">{{if no_cash_coupon}}不使用现金券{{else}}{{if cash_coupon_list && cash_coupon_list[0]}}-￥{{cash_coupon_list[0].coupon_money}}{{else}}暂无可用现金券{{/if}}{{/if}}</div>',
                '</a>',
            '</div>',
            /* 索要发票 */
            '<div class="weui_cells weui_cells_access invoice">',
                '<a href="/#shopping/invoice" class="weui_cell">',
                    '<div class="weui_cell_primary">索要发票</div>',
                    '<div class="weui_cell_ft">',
                        '{{if invoice.need_invoice == "1"}}',
                            '{{if invoice.invoice_type == "1"}}普通发票－{{if invoice.title_type == "1"}}个人{{else}}公司{{/if}}{{else}}增值税发票{{/if}}',
                        '{{else}}',
                            '不需要',
                        '{{/if}}',
                    '</div>',
                '</a>',
            '</div>',
            /* 商品信息 */
            '{{each order_list as orders i}}',
                '<div class="weui_cells item-list">',
                    // 标题
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary">商品清单</div>',
                        '<div class="weui_cell_ft">共{{orders.head_info.sku_count}}件</div>',
                    '</div>',
                    // 配送信息
                    //'<div class="weui_cell">',
                    //    '<div class="weui_cell_primary">',
                    //        '<span class="index-info">配送{{i+1}}</span>',
                    //        '<span class="delivery-info">由望京仓库发货</span>',
                    //    '</div>',
                    //    '<div class="weui_cell_ft">-￥20</div>',
                    //'</div>',
                    // 商品详情
                    '{{each orders.detail_list as detail n}}',
                        '<div class="item-info weui_cell{{if detail.counter > 4}} item-info-more hide{{/if}}">',
                            '<div class="weui_cell_primary">',
                                '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'" {{if detail.img_list[0]}} data-src="{{detail.img_list[0][imgScale]}}"{{/if}}/></div>',
                                '<div class="item-desc">',
                                    '<p>',
                                    '{{if detail.sale_type==3}}<span class="package-item-flag">【套餐】</span>{{/if}}',

                                    '{{if detail.black_tags && detail.black_tags.length > 0 }}',
                                        '{{each detail.black_tags as black_tag}}',
                                           '<span style="color: {{ black_tag.bgcolor | formatColor }}">【{{black_tag.name}}】</span>',
                                        '{{/each}}',
                                    '{{/if}}',
                                    '{{detail.sku_name}}</p>',
                                '</div>',
                            '</div>',
                            '<div class="weui_cell_ft">',
                                '<span class="price">￥{{detail.saled_price}}</span>',
                                '<span>* {{detail.qty}}</span>',
                            '</div>',
                        '</div>',
                        '{{each detail.give_list as give}}',
                            '<div class="gift item-info weui_cell{{if give.counter > 4}} item-info-more hide{{/if}}">',
                                '<div class="weui_cell_primary">',
                                    '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'"{{if give.promo_detail.give_sku_info.img_list[0]}} data-src="{{give.promo_detail.give_sku_info.img_list[0][imgScale]}}"{{/if}}/></div>',
                                    '<div class="item-desc"><p>【赠品】{{give.promo_detail.give_sku_info.name}}</p></div>',
                                '</div>',
                                '<div class="weui_cell_ft">',
                                    '<span class="price">￥0.00</span>',
                                    '<span>* {{give.real_give_qty}}</span>',
                                '</div>',
                            '</div>',
                        '{{/each}}',
                        '{{if detail.package_info}}',
                            '<div class="item-info weui_cell package-item-title {{if detail.package_info.counter > 4}} item-info-more hide{{/if}}"><span class="text">套餐明细</span></div>',
                            '{{each detail.package_info.item_list as packageItem p}}',
                                '<div class="package item-info weui_cell{{if packageItem.counter > 4}} item-info-more hide{{/if}}">',
                                    '<div class="weui_cell_primary">',
                                    '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'"{{if packageItem.img_list[0]}} data-src="{{packageItem.img_list[0][imgScale]}}"{{/if}}/></div>',
                                    '<div class="item-desc"><p>{{packageItem.sku_name}}</p></div>',
                                    '</div>',
                                    '<div class="weui_cell_ft">',
                                    '<span class="price">￥{{packageItem.package_price}}</span>',
                                    '<span>* {{packageItem.qty}}</span>',
                                    '</div>',
                                '</div>',
                            '{{/each}}',
                        '{{/if}}',
                    '{{/each}}',
                    '{{if orders.detail_list.counter > 3}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary"></div>',
                            '<div class="weui_cell_ft action view-all">查看全部</div>',
                            '<div class="weui_cell_ft action view-minor hide">收起全部</div>',
                        '</div>',
                    '{{/if}}',
                '</div>',
                /* 其它信息 */
                '<div class="weui_cells price-list">',
                    //'<div class="weui_cell">',
                    //    '<div class="weui_cell_primary">价格清单</div>',
                    //'</div>',
                    //'<div class="weui_cell small-cell">',
                    //    '<div class="weui_cell_primary">商品总额</div>',
                    //    '<div class="weui_cell_ft">￥70</div>',
                    //'</div>',
                    //'<div class="weui_cell small-cell">',
                    //    '<div class="weui_cell_primary">满减活动</div>',
                    //    '<div class="weui_cell_ft">￥70</div>',
                    //'</div>',
                    '{{if orders.head_info.coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">满减</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary">总计</div>',
                        '<div class="weui_cell_ft">￥{{orders.head_info.activity_money}}</div>',
                    '</div>',

                    '{{if orders.head_info.discount_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">折扣优惠{{if orders.head_info.discount_coupon_money != 0}}（{{orders.head_info.discount_ratio}}折）{{/if}}</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.discount_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.ticket_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">优惠券</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.ticket_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.cash_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">现金券</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.cash_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.floor_money && orders.head_info.floor_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">预估抹零</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.floor_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary">应付</div>',
                        '<div class="weui_cell_ft pay-total">￥{{orders.head_info.money}}</div>',
                    '</div>',
                    //'<div class="weui_cell small-cell">',
                    //    '<div class="weui_cell_primary">配送1</div>',
                    //    '<div class="weui_cell_ft">￥70.20</div>',
                    //'</div>',
                    //'<div class="weui_cell small-cell">',
                    //    '<div class="weui_cell_primary">配送2</div>',
                    //    '<div class="weui_cell_ft">￥30.20</div>',
                    //'</div>',
                '</div>',
            '{{/each}}',
            '<div class="summary">',
                '<span class="pay-mode-title">货到付款</span>',
                '<span class="f-right">',
                    '<span class="price">',
                        // '<del class="origin-price {{if +order_info.origin_money<=+order_info.money}}hidden{{/if}}">原价:￥{{order_info.origin_money}}</del>',
                        '<span class="total-price" data-price="{{order_info.money}}">￥{{order_info.money}}</span>',
                    '</span>',
                    '<button class="operation">确认下单</button>',
                '</span>',
            '</div>',
            '<form method="get" action="/shopping/order/pay" style="display: none;">',
                '<input type="hidden" name="order_id" class="form-order-id" />',
                '<input type="hidden" name="pay_way" class="form-pay-way" />',
            '</form>',
        // '</div>'
    ].join("")
};

module.exports = tpls;
