var commonHeader = require('home:widget/ui/header/header.js');
var main = [
    '<div class="weui_cells_title">发票类型</div>',
        '<div class="weui_cells">',
            '<label class="weui_cell weui_check_label">',
                '<div class="weui_cell_primary">普通发票</div>',
                '<div class="weui_cell_hd weui_cells_checkbox">',
                    '<input type="radio" class="weui_check invoice-type-normal" name="invoice_type" value="1"{{if !invoice_type || invoice_type == "1"}}  checked="checked"{{/if}}>',
                    '<i class="weui_icon_checked"></i>',
                '</div>',
            '</label>',
            '<label class="weui_cell weui_check_label">',
                '<div class="weui_cell_primary">增值税发票</div>',
                '<div class="weui_cell_hd weui_cells_checkbox">',
                    '<input type="radio" class="weui_check" value="2" name="invoice_type"{{if invoice_type == "2"}}  checked="checked"{{/if}}>',
                    '<i class="weui_icon_checked"></i>',
                '</div>',
            '</label>',
        '</div>',
        '<div class="normal">',
            '<div class="weui_cells_title">开票方式</div>',
            '<div class="weui_cells">',
                '<label class="weui_cell weui_check_label">',
                    '<div class="weui_cell_primary">纸质发票</div>',
                    '<div class="weui_cell_hd weui_cells_checkbox">',
                        '<input type="radio" class="weui_check" name="show_type" value="1"{{if !show_type || show_type == "1"}}  checked="checked"{{/if}}>',
                        '<i class="weui_icon_checked"></i>',
                    '</div>',
                '</label>',
            '</div>',
            '<div class="weui_cells_title">发票抬头</div>',
            '<div class="weui_cells">',
                '<label class="weui_cell weui_check_label">',
                    '<div class="weui_cell_primary">个人</div>',
                    '<div class="weui_cell_hd weui_cells_checkbox">',
                        '<input type="radio" class="weui_check" name="title_type" value="1"{{if !title_type || title_type == "1"}}  checked="checked"{{/if}}>',
                        '<i class="weui_icon_checked"></i>',
                    '</div>',
                '</label>',
                '<label class="weui_cell weui_check_label">',
                    '<div class="weui_cell_primary">公司</div>',
                    '<div class="weui_cell_hd weui_cells_checkbox">',
                        '<input type="radio" class="weui_check invoice-title-corp" value="2" name="title_type"{{if title_type == "2"}}  checked="checked"{{/if}}>',
                        '<i class="weui_icon_checked"></i>',
                    '</div>',
                '</label>',
                '<div class="weui_cell invoice-corp{{if !company_name}} hide{{/if}}">',
                    '<div class="weui_cell_primary">单位名称</div>',
                    '<div class="weui_cell_hd">',
                        '<input class="weui_input company-name" type="text" placeholder="请输入单位名称" name="company_name" value="{{company_name}}">',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="weui_cells_title">发票内容</div>',
            '<div class="weui_cells">',
                '{{each content_types as content key}}',
                    '<label class="weui_cell weui_check_label">',
                        '<div class="weui_cell_primary">{{content}}</div>',
                        '<div class="weui_cell_hd weui_cells_checkbox">',
                            '<input type="radio" class="weui_check" name="content_type" value="{{key}}"{{if !content_type && key == "1" || content_type == key}}  checked="checked"{{/if}}>',
                            '<i class="weui_icon_checked"></i>',
                        '</div>',
                    '</label>',
                '{{/each}}',
            '</div>',
        '</div>',
        '<div class="vat">',
            '提示：<br/><br/>',
            '1. 增值税发票将在订单完成收货后10个工作日开出；<br/>',
            '2. 不在贵公司营业执照经营范围内的食品饮料酒类、服装鞋帽、母婴、化妆品等商品不能开具增票，开具前请核对您的经营范围；<br/>',
            '3. 同一公司多个订单索取增值税发票，我们会根据实际情况，开具成一张增值税发票；<br/>',
            '4. 增值税发票只开具您购买的商品明细。<br/>',
        '</div>'
].join('');

module.exports = {
    content: [
        // '<div class="mod-invoice">',
            commonHeader({
              title: '发票信息',
              backUrl: '/#shopping/order'
            }),
            '<div class="weui_cells">',
                '<label class="weui_cell weui_check_label">',
                    '<div class="weui_cell_primary">是否需要开发票</div>',
                    '<div class="weui_cell_hd weui_cells_checkbox">',
                        '<input type="checkbox" class="weui_check need-invoice" name="need_invoice"{{if need_invoice == "1"}} checked="checked"{{/if}}>',
                        '<i class="weui_icon_checked"></i>',
                    '</div>',
                '</label>',
            '</div>',
            '<div class="main{{if invoice_type == "2"}} type-vat{{/if}}">',
                '{{if need_invoice == "1"}}',
                    main,
                '{{/if}}',
            '</div>',
            '<button class="weui_btn weui_btn_primary btn-confirm">确认</button>',
            '<div class="tip">',
                '<br/>提示：<br/><br/>',
                '发票金额为现金支付金额（扣除优惠券、礼品卡、会员积分等）。<br/>开具的发票会在订单完成后发送，请您确认发票类型与抬头。',
            '</div>',
        // '</div>'
    ].join(''),
    main: main
};
