module.exports = {
    'main': [
        '<header class="header search-header">',
            /*'<i class="icon i-back"></i>',*/
            '<i class="cancel">取消</i>',
            '<form class="search-box" action="">',
                '<i class="iconf i-search"></i>',
                '<input type="search" class="weui_input search-input" placeholder="请输入您要搜索的商品" autocomplete="off"/>',
                '<i class="iconf i-clear"></i>',
                '<i class="iconf i-scan hide"></i>',
            '</form>',
        '</header>',
        // '<div class="main">',
            '<div class="result hide">',
                '<div class="list"></div>',
                '<div class="loading hide">数据加载中...</div>',
            '</div>',
            '<div class="tool">',
                '<div class="no-result hide">',
                    '<i class="iconf i-about"></i>',
                    '抱歉，未找到相关商品，请更换搜索关键词',
                '</div>',
                '<div class="hot-query">',
                    '<h2 class="title">热门搜索</h2>',
                    '<div class="content">',
                        '{{each hot_query_list as item}}',
                            '<span class="query-word">{{item.query}}</span>',
                        '{{/each}}',
                    '</div>',
                '</div>',
                '<div class="history hide">',
                    '<h2 class="title">搜索历史</h2>',
                    '<ul class="list"></ul>',
                    '<div class="clear">清空</div>',
                '</div>',
            '</div>',
        // '</div>',
    ].join(''),
    'history': [
        '{{each list as item}}',
            '<li class="history-item">{{item}}</li>',
        '{{/each}}'
    ].join(''),
    tips: [
        '<a class="tips" href="{{url}}">',
            '<span class="tips-l">{{txt}}</span>',
            '<span class="tips-r">点击查看<i class="iconf i-arrow-r"></i></span>',
        '</a>',
    ].join('')
};
