var commonHeader = require('home:widget/ui/header/header.js');
var tpls = {
    content: [
        // '<div class="mod-my-order-view">',
            commonHeader({
              title: '{{title}}',
              backUrl: '{{backUrl}}'
            }),
            '{{if type == "view"}}',
                '<div class="weui_cells">',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary order-status">{{order_info.status_name}}{{if order_info.type == "2"}}<span class="type">补单</span>{{/if}}</div>',
                        '<div class="weui_cell_ft">',
                            '<div>订单号：{{order_info.order_id}}</div>',
                            '<div>{{order_info.ordered_at | date_filter}}</div>',
                        '</div>',
                    '</div>',
                '</div>',
                /* 收货地址 */
                '<div class="weui_cells weui_cells_access">',
                    '<div class="address weui_cell">',
                        '<div class="weui_cell_primary">',
                            '<i class="icon i-order-address"></i>',
                            '<div class="address-info" data-id="{{order_info.address_info.address_id}}">',
                                '<p class="contact-info">{{order_info.address_info.contact_name}} {{order_info.address_info.contact_phone}}</p>',
                                '<p class="detail-info">',
                                    '{{order_info.address_info.province_name+order_info.address_info.city_name+order_info.address_info.county_name+order_info.address_info.address}}',
                                '</p>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
                /* 支付方式 */
                '<div class="weui_cells">',
                    '<div class="pay-mode weui_cell">',
                        '<div class="weui_cell_primary">{{order_info.pay_method.title}}</div>',
                        '<div class="weui_cell_ft">{{order_info.pay_method.value}}</div>',
                    '</div>',
                '</div>',
                /* 发票信息 */
                '{{if order_info.invoice_info}}',
                    '<div class="weui_cells invoice">',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">发票信息</div>',
                            '<div class="weui_cell_ft">{{if order_info.invoice_info.invoice_type == "2"}}{{order_info.invoice_info.invoice_type_name}}{{else}}{{order_info.invoice_info.show_type_name}}{{/if}}</div>',
                        '</div>',
                        '{{if order_info.invoice_info.invoice_type == "1"}}',
                            '<div class="prop">发票抬头：{{if order_info.invoice_info.title_type == "2"}}{{order_info.invoice_info.company_name}}{{else}}{{order_info.invoice_info.title_type_name}}{{/if}}</div>',
                            '<div class="prop">发票内容：{{order_info.invoice_info.content_type_name}}</div>',
                        '{{/if}}',
                    '</div>',
                    '{{/if}}',
            '{{/if}}',
            /* 商品信息 */
            '{{#itemList}}',
            '<div class="weui_cells item-list" id="myEvaluate" style="display:none">',
              '<div class="evaluate-title">',
                '<div class="el-item">我的评价</div></div>',
                '<div class="evaluate-star"></div>',
            '</div>',
            '{{if type == "view"}}',
                /* 其它信息 */
                '<div class="summary weui_cell_ft">',
                    '{{if order_info.extend_status.buy_again}}',
                        '<button class="operation reorder">再次购买</button>',
                    '{{/if}}',
                    '{{if order_info.extend_status.add}}',
                            '<button class="operation add">追加补单</button>',
                    '{{/if}}',
                    '{{if order_info.extend_status.cancel}}',
                            '<button class="operation cancel">取消订单</button>',
                    '{{/if}}',
                '</div>',
            '{{/if}}',
        // '</div>'
    ].join(''),
    itemList: [
        '{{each order_list as orders i}}',
            '<div class="weui_cells item-list">',
                // 标题
                '<div class="weui_cell">',
                    '<div class="weui_cell_primary">{{if type == "view"}}配送{{i+1}}{{else}}{{orders.head_info.order_name}}{{/if}}</div>',
                    '<div class="weui_cell_ft">共{{orders.head_info.sku_count}}件</div>',
                '</div>',
                // 商品详情
                '{{each orders.detail_list as detail n}}',

                    '{{if type != "view" || (type == "view" && detail.counter < 3)}}',
                        '<div class="item-info weui_cell{{if type == "view" && detail.counter > 2}} item-info-more hide{{/if}}">',
                            '<div class="weui_cell_primary">',
                                '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'"{{if detail.img_list[0]}} data-src="{{detail.img_list[0][imgScale]}}"{{/if}}/></div>',
                                '<div class="item-desc"><p>{{if detail.sale_type==3 && detail.tags}}<span class="package-item-flag">【{{detail.tags.join("")}}】</span>{{/if}}{{detail.sku_name}}</p></div>',
                            '</div>',
                            '<div class="weui_cell_ft">',
                                '<span class="price">￥{{detail.price}}</span>',
                                '<span>* {{if detail.sale_type==3}}{{detail.qty}}{{else}}{{detail.detail_qty}}{{/if}}</span>',
                            '</div>',
                        '</div>',
                        '{{if type != "view" || (detail.give_list && detail.give_list.counter < 3)}}',
                            '{{each detail.give_list as give}}',
                                '<div class="gift item-info weui_cell">',
                                    '<div class="weui_cell_primary">',
                                        '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'"{{if give.promo_detail.give_sku_info.img_list[0]}} data-src="{{give.promo_detail.give_sku_info.img_list[0][imgScale]}}"{{/if}}/></div>',
                                        '<div class="item-desc"><p>【赠品】{{give.promo_detail.give_sku_info.name}}</p></div>',
                                    '</div>',
                                    '<div class="weui_cell_ft">',
                                        '<span class="price">￥0.00</span>',
                                        '<span>* {{give.real_give_qty}}</span>',
                                    '</div>',
                                '</div>',
                            '{{/each}}',
                        '{{/if}}',
                        '{{if detail.package_info && detail.package_info.item_list.length > 0 && (type != "view" || detail.package_info.counter < 3)}}',
                            '<div class="item-info weui_cell package-item-title"><span class="text">套餐明细</span></div>',
                            '{{each detail.package_info.item_list as packageItem p}}',
                                '{{if type != "view" || packageItem.counter < 3}}',
                                    '<div class="package item-info weui_cell">',
                                        '<div class="weui_cell_primary">',
                                        '<div class="item-img"><img class="lazy-load-img" src="'+__uri('/static/img/holder.png')+'"{{if packageItem.img_list[0]}} data-src="{{packageItem.img_list[0][imgScale]}}"{{/if}}/></div>',
                                        '<div class="item-desc"><p>{{packageItem.sku_name}}</p></div>',
                                        '</div>',
                                        '<div class="weui_cell_ft">',
                                        '<span class="price">￥{{packageItem.package_price}}</span>',
                                        '<span>* {{packageItem.qty}}</span>',
                                        '</div>',
                                    '</div>',
                                '{{/if}}',
                            '{{/each}}',
                        '{{/if}}',
                    '{{/if}}',
                '{{/each}}',
                // 配送单状态及收起展开按钮
                '{{if type == "view"}}',
                    '<div class="weui_cell">',
                       '<div class="weui_cell_primary order-status">{{if orders.head_info && orders.head_info.shipping_status_name}}{{orders.head_info.shipping_status_name}}{{/if}}</div>',
                       // '{{if orders.detail_list.length > 2}}',
                       //     '<div class="weui_cell_ft action view-all">查看全部</div>',
                       //     '<div class="weui_cell_ft action view-minor hide">收起</div>',
                       // '{{/if}}',
                        '<div>',
                            '<a class="weui_cell_ft action view-detail" href="/#my/order/detail?order_id={{orders.head_info.order_id}}">查看详情</a>',
                            '{{if orders.head_info.extend_status.comment}}',
                            '<a class="goto-eveluate weui_cell_ft" href="/#my/order/comment?order_id={{orders.head_info.order_id}}" data-order-id="{{orders.head_info.order_id}}">去评价</a>',
                            '{{/if}}',
                        '</div>',
                    '</div>',
                '{{/if}}',
                // 支付信息
                '{{if type != "view"}}',    //用于详情的case,flag 1 key标红 , 2 value标红 , 3都标红;
                    '{{each orders.footer as f}}',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary{{if f.flag == 1 || f.flag == 3}} flag-red{{/if}}">{{f.key}}</div>',
                        '<div class="weui_cell_ft{{if f.flag == 2 || f.flag == 3}} flag-red{{/if}}">{{f.value}}</div>',
                    '</div>',
                    '{{/each}}',
                '{{else}}',
                    '{{if orders.head_info.coupon_money && orders.head_info.coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">满减</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary">总计</div>',
                        '<div class="weui_cell_ft">￥{{orders.head_info.activity_money}}</div>',
                    '</div>',
                    '{{if orders.head_info.delivery_money && orders.head_info.delivery_money.length}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">发货总计</div>',
                            '<div class="weui_cell_ft">￥{{orders.head_info.activity_money_shipping}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.receipt_money && orders.head_info.receipt_money.length}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">签收总计</div>',
                            '<div class="weui_cell_ft">￥{{orders.head_info.activity_money_receipt }}</div>',
                        '</div>',
                    '{{/if}}',

                    '{{if orders.head_info.discount_coupon_money && orders.head_info.discount_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">{{if type == "view"}}折扣优惠{{if orders.head_info.discount_coupon_money != 0}}（{{orders.head_info.discount_ratio}}折）{{/if}}{{else}}{{orders.head_info.discount_ratio}}{{/if}}</div>',
                            '<div class="weui_cell_ft">{{if type == "view"}}-￥{{/if}}{{orders.head_info.discount_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.ticket_coupon_money && orders.head_info.ticket_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">优惠券</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.ticket_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.cash_coupon_money && orders.head_info.cash_coupon_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">现金券</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.cash_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.floor_money && orders.head_info.floor_money != 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">{{if orders.head_info.extend_status.pay_complete}}抹零{{else}}预估抹零(以实际签收为准){{/if}}</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.floor_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.pay_coupon_money > 0}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">在线支付立减</div>',
                            '<div class="weui_cell_ft">-￥{{orders.head_info.pay_coupon_money}}</div>',
                        '</div>',
                    '{{/if}}',
                    '{{if orders.head_info.money}}',
                        '<div class="weui_cell">',
                            '<div class="weui_cell_primary">应付</div>',
                            '<div class="weui_cell_ft pay-total">￥{{orders.head_info.money}}</div>',
                        '</div>',
                    '{{/if}}',
                '{{/if}}',

                // 支付按钮
                '{{if type == "view"}}',
                    '<div class="weui_cell">',
                        '<div class="weui_cell_primary">',
                            '{{if orders.head_info.extend_status.pay && pay_tips}}',
                            '<span class="tips">{{pay_tips}}</span>',
                            '{{/if}}',
                        '</div>',
                        '{{if orders.head_info.extend_status.pay}}',
                            '<button class="confirm-pay" data-order-id="{{orders.head_info.order_id}}">确认收货并支付</button>',
                        '{{else}}',
                            '<div>{{orders.head_info.status_name}}</div>',
                        '{{/if}}',
                    '</div>',
                '{{/if}}',
            '</div>',
        '{{/each}}'
    ].join('')
};

module.exports = tpls;
