
var tpls = {
    'uiBar': [
        '<div class="weui_search_bar" id="search_bar">',
            '<form class="weui_search_outer">',
                '<div class="weui_search_inner">',
                    '<i class="weui_icon_search"></i>',
                    '<input type="search" class="weui_search_input" id="search_input" value="{{q}}" placeholder="按超市名称/联系方式搜索">',
                    '<a href="javascript:" class="weui_icon_clear" id="search_clear"></a>',
                '</div>',
                '<label for="search_input" class="weui_search_text" id="search_text" style="{{if q}}display: none;{{/if}}">',
                    '<i class="weui_icon_search"></i>',
                    '<span>按超市名称搜索</span>',
                '</label>',
            '</form>',
            '<a href="javascript:" class="weui_search_cancel" id="search_cancel">取消</a>',
        '</div>',
        '<div class="weui_tab">',
            '<div class="weui_navbar">',
                '<div class="weui_navbar_item{{if !tab || tab=="visitplan"}} weui_bar_item_on{{/if}}" data-tab="visitplan">',
                    '超市拜访计划',
                '</div>',
                '<div class="weui_navbar_item{{if tab=="markplan"}} weui_bar_item_on{{/if}}" data-tab="markplan">',
                    '超市打点计划',
                '</div>',
                '<div class="weui_navbar_item{{if tab=="viewmap"}} weui_bar_item_on{{/if}}" data-tab="viewmap">',
                    '<i class="iconfont icon-ditu"></i>查看地图',
                '</div>',
            '</div>',
            '<div class="weui_tab_bd">',
                '{{if (tab && tab=="visitplan")}}',
                    '<div class="tab-content-visitplan">',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="noOrder"}} weui_btn_primary{{else}} weui_btn_default{{/if}}" data-tag="noOrder">历史0单</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="scilent"}} weui_btn_primary{{else}} weui_btn_default{{/if}}" data-tag="scilent">近期沉睡</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="a"}} weui_btn_primary{{else}} weui_btn_default{{/if}} letter-type" data-tag="a">A类</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="b"}} weui_btn_primary{{else}} weui_btn_default{{/if}} letter-type" data-tag="b">B类</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="c"}} weui_btn_primary{{else}} weui_btn_default{{/if}} letter-type" data-tag="c">C类</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="d"}} weui_btn_primary{{else}} weui_btn_default{{/if}} letter-type" data-tag="d">D类</a>',
                    '</div>',
                '{{else if (tab && tab=="markplan")}}',
                    '<div class="tab-content-markplan">',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="nopoint"}} weui_btn_primary{{else}} weui_btn_default{{/if}}" data-tag="nopoint">未打点超市</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="point"}} weui_btn_primary{{else}} weui_btn_default{{/if}}" data-tag="point">已打点超市</a>',
                        '<a href="javascript:;" class="weui_btn weui_btn_mini tag{{if tag=="lackinfo"}} weui_btn_primary{{else}} weui_btn_default{{/if}}" data-tag="lackinfo">基本信息不全</a>',
                    '</div>',
                '{{/if}}',
            '</div>',
        '</div>'
    ].join(''),
    'main': [
        '<header class="header">',
            '<h1>我的超市</h1>',
            '{{if level == "6"}}',
                '<div class="act-select-people"><i class="iconfont icon-iconshaixuan"></i><span class="selected-people"></span></div>',
            '{{/if}}',
        '</header>',
        '<div class="ui-bar"></div>',
        '<ul class="data-list"></ul>',
        '<div class="map-wrap"></div>',
    ].join(''),
    'list': [
        '{{if (total && total.render && total.type) || (querys.flag && renderTotal)}}',
            '<p class="type-count">数量: {{total.count || total}}</p>',
        '{{/if}}',
        '{{each list as item index}}',
            '<li class="weui_cells data-item market-item" data-address_id="{{item.address_id}}">',
            '<p>超市名称: {{item.market_name}}</p>',
            '<p>联系人: {{item.contact_name}}</p>',
            '<p>联系方式: {{item.contact_phone}}</p>',
            '<p>超市地址: {{item.address}}</p>',
        '{{if type}}',
        '<div class="sum">',
                '{{if item.sales_terminal_v13_hist0_visit_tasklist_register_date}}',
                '<p>注册时间: {{item.sales_terminal_v13_hist0_visit_tasklist_register_date}}</p>',
                '{{else}}',
                '<p>最近下单距今天数: {{item.sales_terminal_v13_deep_sleep_tasklist_day_diff_nums}}</p>',
                '{{/if}}',
                '<p>最近拜访时间: {{item.sales_terminal_v13_hist0_visit_tasklist_recent_visit_date || item.sales_terminal_v13_deep_sleep_tasklist_recent_visit_date1}}</p>',
        '</div>',
        '{{else}}',
            '{{if item.muid}}',
                '<div class="sum">',
                    '<p>用户属性: {{item.sales_terminal_v13_user_type_in_30days_tag}}类用户</p>',
                    '<p>过去30天下单次数: {{item.sales_terminal_v13_user_type_in_30days_orders_in_30_days}}</p>',
                    '<p>累计下单金额: {{item.sales_terminal_v13_user_type_in_30days_all_order_money}}</p>',
                '</div>',
            '{{/if}}',
        '{{/if}}',
        '</li>',
        '{{/each}}'
    ].join(''),
    'taskType': [
        '{{each taskType as item}}',
            '<div class="task-content" data-type="{{item.type}}">',
                '<span class="task-type"><span class="{{if item.type == "N"}}unfinish{{/if}}">{{item.name}}</span><span class="num {{if item.type == "N"}}unfinish{{/if}}">{{item.count}}</span></span>',
                '<div class="list-content {{item.type}}"></div>',
            '</div>',
        '{{/each}}'
    ].join(''),
    empty: ['<li class="item-empty">暂无数据</li>'].join(''),
    end: ['<li class="item-to-end">没有更多数据了</li>'].join('')
};
module.exports = tpls;