var commonHeader = require('home:widget/ui/header/header.js');
module.exports = {
    'content': [
        commonHeader({
          backUrl: '/#my',
          title: '关于'
        }),
        '<div class="logo icon i-logo">',
            '<div class="version"></div>',
        '</div>',
        '<div class="content">',
            '<div class="title">关于链商优供</div>',
            '<div class="paragraph">',
                '<p class="p-title">配送</p>',
                '您在提交订单时需选择“配送地址”，链商优供会将商品送到您的指定地点',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">配送时间</p>',
                '链商优供会根据您的收货地址系统判定配送时间',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">配送范围</p>',
                '链商优供会根据您所填写收货地址进行系统判定',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">货到付款</p>',
                '您收货后可在app确认收货并选择“微信、支付宝、pos机刷卡”进行支付',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">支付问题</p>',
                '我通过网上支付了，为什么订单显示未支付？<br/>',
                '请您先查看您的交易记录，确认款项是否成功支付。<br/>',
                '若款项未成功支付，请您在 “我的订单”找到该订单页面重新支付即可；<br/>',
                '若款项已成功支付，请您联系“链商优供客服热线”400-711-5858（工作时间 09:00 - 18:00）处理。',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">配送问题</p>',
                '订单已提交成功，什么时候可以收到商品？<br/>',
                '订单提交成功后我们会按照系统判定及仓库出货时间先后进行配送，您可以在“我的订单”查看订单状态，或拨打“链商优供客服热线”400-711-5858（工作时间 09:00 - 18:00），进行咨询。<br/>',
                '签收时发现商品外包装破损，该如何处理？<br/>',
                '如您收到商品后尚未签收，发现外包装有破损，您可直接拒收。',
            '</div>',
            '<div class="paragraph">',
                '<p class="p-title">意见反馈</p>',
                '您的批评和建议将能更好的帮助我们完善产品。您可以将需要反馈的内容说明并发送至service@lsh123.com，我们会尽快处理。',
            '</div>',
        '</div>'
    ].join('')
};
