var commonHeader = require('home:widget/ui/header/header.js');
var tpls = {
    itemViewCanvas: [
        commonHeader({
          title: '商品详情',
          extendTpl: '<span class="iconf i-collect-star-empty collect"></span>'
        }),

        '<section class="item-detail-img slide" style="width: 100%">',
            //'<img class="img"  {{if item.sku_info.img_list[0]}} src="{{item.sku_info.img_list[0].large}}"{{/if}}/>',
        '</section>',

        '<section class="item-detail-brief clearfix">',
            '<h2>{{item.sku_info.name}}</h2>',
            // 价格区域
            '<div class="wrapper-main">',
              '<div class="wrapper">',
                  '<span class="current-price">{{item.currentPrice | formatPrice}}</span>',
                  '{{if item.deletePrice}}',
                      '<del>{{item.deletePrice | formatPrice}}</del>',
                  '{{/if}}',
              '</div>',
              '<div class="wrapper wrapper-r">',
                  '{{if item.promo_info.sale && item.promo_info.sale.promo_type == "5"}}',
                      '<span class="seckill_time">',
                          '{{if item.timeValid == 1}}',
                              '{{item.promo_info.sale.begin_at | stampFormat:"yyyy-MM-dd hh:mm"}}秒杀开始',
                          '{{else if item.timeValid == 2}}',
                              '已经结束',
                          '{{else}}',
                              '{{item.promo_info.sale.end_at | stampFormat:"hh:mm"}}秒杀结束',
                          '{{/if}}',
                      '</span>',
                      '<span class="seckill_sale">',
                          '已售{{item.promo_info.sale.kill_process}}%',
                          '<span class="progress"><span class="value" style="width: {{item.promo_info.sale.kill_process}}%"></span></span>',
                      '</span>',
                  '{{/if}}',
                  '{{if item.promo_info.sale && item.promo_info.sale.promo_type == "1" && item.promo_info.sale.end_at}}',
                      '<span class="promo_end">{{item.promo_info.sale.end_at | datetime_filter}}恢复原价</span>',
                  '{{/if}}',
                  '{{if item.sale_info.moq > 1}}',
                      '<span class="moq">{{item.sale_info.moq}}{{item.sale_info.sale_unit_name || "件"}}起售</span>',
                  '{{/if}}',
              '</div>',
            '</div>',
            // 商品所在的活动（满减、秒杀...）
            '{{if item.promo_info && item.promo_info.activity_list && item.promo_info.activity_list.length > 0}}',
              '{{each item.promo_info.activity_list as activity}}',
                '<div class="item-detail-activity">',
                    '<a href="{{if activity.promo_type == "5"}}/#seckill{{else}}/#home/activity?activity_id={{activity.id}}{{/if}}">',
                        '<span class="tag" style="background-color:{{activity.bgcolor | formatColor}}">{{activity.promo_type_name}}</span>',
                        '<span class="name">{{activity.name}}</span>',
                        '<i class="iconf i-arrow-r"></i>',
                    '</a>',
                '</div>',
              '{{/each}}',
            '{{/if}}',
            '{{if item.sale_info && item.sale_info.black_tags && item.sale_info.black_tags[0]}}',
              '<div class="item-detail-activity">',
                '<span class="black-tag" style="background-color: {{item.sale_info.black_tags[0].bgcolor | formatColor}}">{{item.sale_info.black_tags[0].name}}<span>',
              '</div>',
            '{{/if}}',
            // 赠品
            '{{if item.promo_info && item.promo_info.give_list}}',
                '<div class="item-gift">',
                    '{{each item.promo_info.give_list as give}}',
                        '<a href="/#category/item?sku_id={{give.promo_detail.give_sku_id}}">',
                            '<i class="tag tag-{{give.promo_type}}">赠</i>',
                            '<span class="name"><span class="rule">买{{give.promo_detail.buy_qty}}即赠</span>{{give.promo_detail.give_sku_info.name}}',
                            '{{if give.promo_detail.give_qty > 1}}',
                                '<span class="give-qty"> x{{give.promo_detail.give_qty}}</span>',
                            '{{/if}}',
                            '</span>',
                            '<del class="price">{{give.promo_detail.give_sku_info.price}}</del>',
                            '<i class="iconf i-arrow-r"></i>',
                        '</a>',
                    '{{/each}}',
                '</div>',
            '{{/if}}',
        '</section>',
        '{{if item.related_info && item.promo_info.sale && item.promo_info.sale.promo_type == "5"}}',
            '<section class="item-special-seckill">',
                '{{item.related_info.tips}}',
                '<a class="btn" href="/#category/item?sku_id={{item.related_info.origin_sku_id}}">查看非活动商品信息</a>',
            '</section>',
        '{{/if}}',

        '{{if !item.package_info}}',
        '<section class="item-detail-info">',
            '<h2>商品信息</h2>',
            '<ul>',
                '{{each item.prop_list as prop}}',
                '<li>',
                    '<span class="name">{{prop.key}}</span>',
                    '<span class="value">{{prop.value}}</span>',
                '</li>',
                '{{/each}}',
            '</ul>',
        '</section>',
        '{{else}}',
        //TODO 如何处理区分商品tag类别,用于显示套餐
        '<section class="item-package-info">',
            '<h2>套餐信息</h2>',
            '<div class="weui_cells">',
            '{{each item.package_info.item_list as packageItem}}',
                '<a class="weui_cell" href="/#category/item?sku_id={{packageItem.sku_id}}">',
                    '<img alt="{{packageItem.sku_name}}" class="weui_cell_hd lazy-load-img img" src="'+__uri('/static/img/holder.png')+'" {{if packageItem.img_list && packageItem.img_list[0]}} data-src="{{packageItem.img_list[0][imgScale]}}"{{/if}}{{imgScale}}/>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<p>{{packageItem.sku_name}}</p>',
                        '<p>',
                        '{{if packageItem.package_price}}',
                        '<span class="current-price">',
                        '{{packageItem.package_price | formatPrice}}',
                        '</span>',
                        '<del>{{packageItem.sale_price | formatPrice}}</del>',
                        '{{/if}}',
                        '</p>',
                        '<p>',
                        '<span class="name">销售规格</span>',
                        '<span class="value">{{packageItem.sku_spec}}</span>',
                        '</p>',
                        '<p>',
                        '<span class="name">数量</span>',
                        '<span class="value">{{packageItem.sale_unit}}</span>',
                        '</p>',
                        '<p>',
                        '<span class="name">单位</span>',
                        '<span class="value">{{packageItem.sale_unit_name || "件"}}</span>',
                        '</p>',
                    '</div>',
                    '<i class="iconf i-arrow-r weui_cell_ft"></i>',
                '</li>',
            '{{/each}}',
            '</ul>',
        '</section>',
        '{{/if}}',

        '<section class="item-detail-operations">',
            '<a href="/#shopping/cart" class="circle-cart">',
              '<span class="cart-main">',
                '<span class="cart-count"></span>',
                '<i class="iconf i-item-cart"></i>',
                '<span class="cart-price">购物车</span>',
              '</span>',
            '</a>',
            '<div class="operation" data-sku_id="{{item.sku_info.sku_id}}" data-moq="{{item.sale_info.moq}}">',
                '{{if item.sale_info.status == 3 || item.timeValid == 2}}',
                    '<span class="sellout">下架</span>',
                '{{else if item.sale_info.inventory_num == 0 && item.timeValid != 1}}',
                    '<span class="sellout">售罄</span>',
                '{{else if item.timeValid == 1}}',
                    '<span class="sellout">即将开抢</span>',
                '{{else}}',
                    '<span class="buy{{if !item.buy_info.count}} empty{{/if}}">',
                        '<span class="text">',
                        '添加商品:',
                        '</span>',
                        '<i class="act-subtract iconf i-item-subtract"></i>',
                        '<span class="buy-count" data-count="{{item.buy_info.count || 0}}">{{item.buy_info.count || 0}}</span>',
                        // '{{if item.sale_info.moq > 1}}<span class="moq">{{item.sale_info.moq}}件起售</span>{{/if}}',
                        '<i class="act-add iconf i-item-add"></i>',
                    '</span>',
                '{{/if}}',
            '</div>',
        '</section>'
    ].join('')
};

module.exports = tpls;
