var commonHeader = require('home:widget/ui/header/header.js');
var tpl = {
    list: [
        // '<div class="mod-address">',
            commonHeader({
              title: '收货地址',
              backUrl: '/#my'
            }),
            '<div class="weui_cells weui_cells_access addresses">',
                '{{each address_list as address}}',
                    '<a href="/#my/address/edit/{{address.address_id}}" class="weui_cell">',
                        '<div class="weui_cell_primary">',
                            '<p>',
                                '{{address.contact_name}} {{address.contact_phone}}',
                                '{{if address.is_default==1}}',
                                    '&nbsp;&nbsp;<span class="default-flag">默认</span>',
                                '{{/if}}',
                            '</p>',
                            '<p>{{address.province_name+address.county_name+address.address}}</p>',
                        '</div>',
                        '<div class="weui_cell_ft"> </div>',
                    '</a>',
                '{{/each}}',
            '</div>',
            '<a href="/#my/address/add" class="add weui_btn weui_btn_primary">新增收货地址</a>',
        // '</div>'
    ].join(''),
    optionalList: [
        // '<div class="mod-address">',
            commonHeader({
              customBackTpl: '<i class="iconf i-arrow-l i-back back-to-order"></i>',
              title: '选择收货地址',
              extendTpl: '<span class="edit">编辑</span>'
            }),
            '<div class="weui_cells weui_cells_checkbox addresses">',
                '{{each address_list as address index}}',
                    '<label class="weui_cell weui_check_label" for="address{{index}}" data-id={{address.address_id}}>',
                        '<div class="weui_cell_bd weui_cell_primary">',
                            '<p>',
                                '{{address.contact_name}} {{address.contact_phone}}',
                                '{{if address.is_default==1}}',
                                    '&nbsp;&nbsp;<span class="default-flag">默认</span>',
                                '{{/if}}',
                            '</p>',
                            '<p>{{address.province_name+address.county_name+address.address}}</p>',
                        '</div>',
                        '<div class="weui_cell_ft">',
                            '<input type="radio" name="addressRadio" class="weui_check address-radio" id="address{{index}}" {{if address.address_id==selected}}checked="checked"{{/if}}>',
                            '<span class="weui_icon_checked"></span>',
                        '</div>',
                    '</label>',
                '{{/each}}',
            '</div>',
            '<a href="/#my/address/add/true" class="add weui_btn weui_btn_primary">新增收货地址</a>',
        // '</div>'
    ].join(''),
    address: [
        // '<div class="mod-address">',
            commonHeader({
              customBackTpl: '<a href="/#my/address" class="iconf i-arrow-l i-back{{if onChoosing}} back-to-order{{/if}}"></a>',
              title: '{{title}}'
            }),
            '<form class="weui_cells" data-id="{{ars.address_id}}" novalidate="novalidate">',
                '{{if action=="update"}}<input name="address_id" type="hidden" value="{{ars.address_id}}">{{/if}}',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '<span class="im">*</span>收货人',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请填写收货人!" name="contact_name" class="weui_input" type="text" placeholder="请输入收货人姓名" value="{{ars.contact_name}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '<span class="im">*</span>手机号码',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="cellphone" data-msg="请填写正确的手机号!" name="contact_phone" class="weui_input" type="tel" placeholder="请输入手机号码" value="{{ars.contact_phone}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '<span class="im">*</span>超市名称',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请填写超市名称!" name="market_name" class="weui_input" type="text" placeholder="请输入超市名称" value="{{ars.market_name}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '备用电话',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input name="telephone" class="weui_input" type="text" placeholder="请输入备用电话" value="{{ars.telephone}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '<span class="im">*</span>所在地区',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请选择所在地区!" name="area" data-pid="{{ars.province}}" data-cid="{{ars.city}}" data-coid="{{ars.county}}" class="weui_input area-input" type="text" placeholder="请选择所在地区" value="{{if action=="update" }}{{ars.province_name+ars.city_name+ars.county_name}}{{/if}}" readonly>',
                    '</div>',
                '</div>',
                '<div class="weui_cell address">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '<span name="address" class="im">*</span>详细地址',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input pattern="^[\\s\\S]{5,}$" data-msg="请填写详细收货地址!" name="address" class="weui_input" type="text" placeholder="具体到街道、门牌号，不少于5个字" value="{{ars.address}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell address" {{if ars.is_default==1}}style="display:none;"{{/if}}>',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '设为默认地址',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input name="is_default" class="weui_switch" type="checkbox" {{if ars.is_default==1}}checked{{/if}}>',
                    '</div>',
                '</div>',
            '</form>',
            '{{if action=="update" && ars.is_default!=1}}<span class="delete weui_btn weui_btn_primary">删除该地址</span>{{/if}}',
            '<span class="action weui_btn weui_btn_primary" data-action="{{action}}">保存</span>',
            '<div class="weui_dialog_confirm delete-confirm" style="display: none;">',
                '<div class="weui_mask"></div>',
                '<div class="weui_dialog">',
                    '<div class="weui_dialog_hd"><strong class="weui_dialog_title">确认删除?</strong></div>',
                    //'<div class="weui_dialog_bd">自定义弹窗内容，居左对齐显示，告知需要确认的信息等</div>',
                    '<div class="weui_dialog_ft">',
                        '<a class="weui_btn_dialog default cancel">取消</a>',
                        '<a class="weui_btn_dialog primary confirm">确定</a>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="tip">',
                '<br/>提示：<br/><br/>',
                '新增或修改的地址需审核才可下单，审核需要1-3个工作日，如需帮助，请联系客服 400-711-5858。',
            '</div>',
        // '</div>'
    ].join('')
};

module.exports = tpl;
