var commonHeader = require('home:widget/ui/header/header.js');
var tpls = {
    login: [
        '<div class="mod-account-login">',
            commonHeader({
              title: '登录',
              hideBackIcon: true,
              titleCenter: true
            }),
            '<form class="login-box" novalidate="novalidate">',
                '<div class="form-group">',
                    '<label><i class="icon i-account-username"></i></label>',
                    '<input data-vtype="empty" data-msg="请输入用户名!" type="text" name="username" class="weui_input" placeholder="手机号" autocomplete="off"/>',
                    '<i class="icon i-account-clear"></i>',
                '</div>',
                '<div class="form-group">',
                    '<label><i class="icon i-account-password"></i></label>',
                    '<input data-vtype="password" data-msg="请输入合法密码!" type="password" name="password" class="weui_input" placeholder="输入密码, 6-16位字母或数字" autocomplete="off"/>',
                    '<i class="icon i-account-clear"></i>',
                '</div>',
                '<div class="form-group from-verify-code">',
                    '<label><i class="icon i-account-verifycode"></i></label>',
                    '<input type="text" data-vtype="" data-msg="请输入短信验证码!" name="verify_code" class="weui_input verifycode" placeholder="请输入短信验证码" autocomplete="off"/>',
                    '<button class="verify-code weui_btn weui_btn_plain_primary">获取验证码</button>',
                '</div>',
                '<button class="submit weui_btn weui_btn_primary btn" disabled>登录</button>',
                '<a href="/account/user/register" class="regis weui_btn weui_btn_default btn">注册</a>',
                '<a href="/account/user/findpass" class="forget">忘记密码?</a>',
            '</form>',
        '</div>'
    ].join(""),
    pass: [
        '<div class="mod-account-pass">',
            commonHeader({
              backUrl: '/account/user/login',
              title: '忘记密码',
              titleCenter: true
            }),
            '<form class="pass-box">',
                '<div class="form-group">',
                    '<label><i class="icon i-account-username"></i></label>',
                    '<input data-vtype="cellphone" data-msg="请输入正确的手机号!" type="text" name="cellphone" class="weui_input" placeholder="手机号" autocomplete="off"/>',
                    '<i class="icon i-account-clear"></i>',
                '</div>',
                '<div class="form-group">',
                    '<label><i class="icon i-account-password"></i></label>',
                    '<input data-vtype="password" data-msg="请设置新的合法密码!" type="password" name="password" class="weui_input" placeholder="请输入新密码" autocomplete="off"/>',
                    '<i class="icon i-account-clear"></i>',
                '</div>',
                '<div class="form-group">',
                    '<label><i class="icon i-account-verifycode"></i></label>',
                    '<input type="text" data-vtype="empty" data-msg="请输入短信验证码!" name="verify_code" class="weui_input verifycode" placeholder="请输入短信验证码" autocomplete="off"/>',
                '</div>',
                '<button class="submit weui_btn weui_btn_primary btn" disabled>修改密码</button>',
                '<button class="get-code weui_btn weui_btn_plain_primary btn">获取验证码</>',
            '</form>',
        '</div>'
    ].join(""),
    regist: [
        '<div class="mod-account-regist">',
            commonHeader({
              backUrl: '/account/user/login',
              titleCenter: true,
              title: '注册'
            }),
            '<div class="weui_cells" style="display:none;">',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd location-wrap">',
                        '<input name="location" type="text" class="location weui_input" value="定位中..." />',
                    '</div>',
                '</div>',
            '</div>',
            '<form class="weui_cells regist-main-form">',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '手机号',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="cellphone" data-msg="请输入正确的手机号码!" name="cellphone" class="weui_input" type="text" placeholder="请填写手机号" value="{{cellphone}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '姓名',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请输入姓名!" name="name" class="weui_input" type="text" placeholder="请填写姓名" value="{{name}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '超市名称',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请输入超市名称!" name="market_name" class="weui_input" type="text" placeholder="请填写超市名称" value="{{market_name}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '所在地区',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input data-vtype="empty" data-msg="请选择所在区域!" name="area" class="weui_input area-input" type="text" placeholder="请选择所在地区" value="{{area}}" readonly>',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '详细地址',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input pattern="^[\\s\\S]{5,}$" data-msg="请输入详细地址!" name="address" class="weui_input" type="text" value="{{address}}" placeholder="具体到街道、门牌号，不少于5个字">',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '备用电话（非必填）',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input name="emerg_cellphone" class="weui_input" type="text" value="{{emerg_cellphone}}">',
                    '</div>',
                '</div>',
                '<div class="weui_cell">',
                    '<div class="weui_cell_hd">',
                        '<label class="weui_label">',
                            '邀请码（非必填）',
                        '</label>',
                    '</div>',
                    '<div class="weui_cell_bd weui_cell_primary">',
                        '<input name="invite_code" class="weui_input" type="text" value="{{invite_code}}">',
                    '</div>',
                '</div>',
            '</form>',
            '<div class="tip">',
                '<br/>提示：<br/><br/>',
                '未填写邀请码的注册地址需审核才可下单，审核需要1-3个工作日，如需帮助，请联系客服400-711-5858。',
            '</div>',
            '<button class="next weui_btn weui_btn_primary" disabled>下一步</button>',
        '</div>'
    ].join(""),
    registVerify: [
        '<div class="mod-account-regist">',
            commonHeader({
              titleCenter: true,
              title: '注册',
              backClass: 'cancel-verify'
            }),
            '<form class="regist-box">',
                '<div class="form-group">',
                    '<label><i class="icon i-account-username"></i></label>',
                    '<input type="text" class="weui_input" value="{{cellphone}}" disabled/>',
                '</div>',
                '<div class="form-group">',
                    '<label><i class="icon i-account-password"></i></label>',
                    '<input type="password" data-vtype="password" data-msg="请设置合法密码!" name="password" class="weui_input" placeholder="设置密码, 6-16位字母或数字" autocomplete="off"/>',
                '</div>',
                '<div class="form-group">',
                    '<label><i class="icon i-account-verifycode"></i></label>',
                    '<input type="text" data-vtype="empty" data-msg="请输入短信验证码!" name="verify_code" class="weui_input verifycode" placeholder="短信验证码" autocomplete="off"/>',
                '</div>',
                '<button class="submit-regist weui_btn weui_btn_primary btn" disabled>注册</button>',
                '<button class="verify-code weui_btn weui_btn_plain_primary btn">获取验证码</button>',
            '</form>',
            '<div class="agreement">点击“注册” 即同意 <span class="regist-agree">注册协议</span></div>',
        '</div>'
    ].join(""),
    registApprove: [
        '<div class="mod-account-regist">',
            commonHeader({
              hideBackIcon: true,
              title: '注册'
            }),
            '<p class="success-p1">',
                '注册信息已提交!',
            '</p>',
            '<p class="success-p2">',
                '审核通过后, 工作人员会在三个工作日内联系您!谢谢合作!',
            '</p>',
            '<a href="/" class="weui_btn weui_btn_primary btn success-btn">知道了</a>',
        '</div>'
    ].join("")
};

module.exports = tpls;
